const styles = [
  {
    name: "Boring Default",
    path: "default/style.css",
    designer: "Mr. Hinkle",
    portfolio: "https://www.tomhinkle.net",
    highlight: true,
  },
  {
    name: "Golden Ratio",
    path: "th-fib/style.css",
    designer: "Mr. Hinkle",
    portfolio: "https://www.tomhinkle.net",
    highlight: true,
  },
  {
    name: "Block party",
    path: "block-party/style.css",
    designer: "Mr. Hinkle",
    portfolio: "https://www.tomhinkle.net",
    highlight: true,
  },
  {
    path: "ar-tree/style.css",
    designer: "Aarav Patel",
    name: "Fall Tree",
    portfolio: "",
    highlight: true,
  },
  {
    name: "The Cataclysm: as seen by scavenger in sewer",
    path: "pe-ter/style.css",
    designer: "Peter F. Parlee Carr",
    portfolio: "",
  },
  {
    name: "Radio Music",
    path: "emily-music/style.css",
    designer: "Emily Myerov",
    portfolio: "",
    highlight: true,
  },
  {
    name: "Halo",
    path: "nathan-halo/style.css",
    designer: "Nathan E.",
    portfolio: "https://nathans-portfolio-project.netlify.app/",
  },
  {
    name: "clean and simple",
    path: "emanuelly-ferreira/style.css",
    designer: "Emanuelly Ferreira.",
    portfolio: "#",
    highlight: true,
  },
  {
    name: "Milky Way",
    path: "Will/style.css",
    designer: "Will K",
    portfolio: "",
  },
  {
    name: "your design name",
    path: "nai/style.css",
    designer: "Naima Kaldi",
    portfolio:
      "your personal portfolio, if you have one — or claim a URL now on netlify and build on soon :)",
  },
  {
    name: "Simple Dark",
    path: "zander2023/style.css",
    designer: "Zander B-V",
    portfolio: "",
    highlight: true,
  },
  {
    name: "Tri-Tec Industries",
    path: "24-ethan-tritec/style.css",
    designer: "Ethan-Matte",
    portfolio: "https://sunryze-studios.netlify.app/web.html",
  },
  {
    name: "Simplicity",
    path: "24-ethan-simple/style.css",
    designer: "Ethan-Matte",
    portfolio: "https://sunryze-studios.netlify.app/web.html",
    highlight: true,
  },
  {
    name: "Retro Game",
    path: "24-ethan-retro/style.css",
    designer: "Ethan-matte",
    portfolio: "https://sunryze-studios.netlify.app/web.html",
    highlight: true,
  },
  {
    name: "Zen Garden ",
    path: "24-luis-simple/style.css",
    designer: "Luis-Valiente",
    portfolio:
      "your personal portfolio, if you have one — or claim a URL now on netlify and build on soon :)",
  },
  {
    name: "Construction",
    path: "23-julian-construction/style.css",
    designer: "julian-henry",
    portfolio: "https://remarkable-pithivier-572d14.netlify.app/",
    highlight: true,
  },
  {
    name: "Cyberpunk",
    path: "23-julian-cyberpunk/style.css",
    designer: "julian-henry",
    portfolio: "https://remarkable-pithivier-572d14.netlify.app/",
    highlight: true,
  },
  {
    name: "Haunted Graveyard",
    path: "23-julian-haunted/style.css",
    designer: "julian-henry",
    portfolio: "https://remarkable-pithivier-572d14.netlify.app/",
    highlight: true,
  },
  {
    name: "Soaring Sky",
    path: "seth-lupo-soaring-sky/style.css",
    designer: "Seth Lupo",
    portfolio: "https://sethlupo.dev/",
    highlight: true,
  },
  {
    name: "Modernist Blocks",
    path: "seth-lupo-modernist-blocks/style.css",
    designer: "Seth Lupo",
    portfolio: "https://sethlupo.dev/",
    highlight: true,
  },
  {
    name: "Limbo",
    path: "seth-lupo-limbo/style.css",
    designer: "Seth Lupo",
    portfolio: "https://sethlupo.dev/",
    highlight: true,
  },
  {
    name: "Eli's Dark Mode",
    path: "eli-d/style.css",
    designer: "Elijah D",
    portfolio: "",
  },
  {
    name: "Sky",
    path: "avery-sky/style.css",
    designer: "Avery K",
    portfolio: "",
  },
  {
    name: "Space",
    path: "avery-space/style.css",
    designer: "Avery K",
    portfolio: "",
    highlight: true,
  },
  {
    name: "The Theater",
    path: "avery-theater/style.css",
    designer: "Avery K",
    portfolio: "",
    highlight: true,
  },
  {
    name: "Bold Lines",
    path: "owenk/style.css",
    designer: "Owen K",
    portfolio: "",
    highlight: true,
  },
  {
    name: "Space Wide",
    path: "lex-space/style.css",
    designer: "Lex R",
    portfolio: "",
  },
  {
    name: "Beach Wave",
    path: "beach-waves/style.css",
    designer: "Mr. Hinkle",
    portfolio: "https://www.tomhinkle.net",
    highlight: true,
  },
  {
    name: "Stars (by ChatGPT4)",
    path: "stars-gpt/style.css",
    designer: "ChatGPT 4",
    portfolio: "https://chat.openai.com/",
  },
  {
    name: "8-Bit (by ChatGPT4)",
    path: "gpt-8bit/style.css",
    designer: "ChatGPT 4",
    portfolio: "https://chat.openai.com/",
    highlight: true,
  },
  {
    name: "Delicate Touch (by ChatGPT4)",
    path: "delicate-gpt/style.css",
    designer: "ChatGPT 4",
    portfolio: "https://chat.openai.com/",
    highlight: true,
  },
  {
    name: "Stardust",
    path: "stardust-klein/style.css",
    designer: "Sarah K",
    portfolio: "https://sarah-klein-portfolio-shenanigans.netlify.app/",
  },
  {
    name: "Artistry",
    path: "SR-Artisry/style.css",
    designer: "S. Rader",
    portfolio: "#fixme",
  },
  {
    name: "florals",
    path: "RC-Florals/style.css",
    designer: "Ridnie C.",
    portfolio: "https://ridnie-iacs-web-portfolio.netlify.app",
  },
  {
    name: "Circus",
    path: "LL-cirus/style.css",
    designer: "L. Lovell",
    highlight: true,
    portfolio: "https://lovell-web-design-portfolio.netlify.app/",
  },
  {
    name: "Leaves",
    path: "LL-leaves/style.css",
    designer: "L. Lovell",
    portfolio: "https://lovell-web-design-portfolio.netlify.app/",
  },
  {
    name: "Minimalism",
    path: "LL-minimalism/style.css",
    designer: "L. Lovell",
    portfolio: "https://lovell-web-design-portfolio.netlify.app/",
  },
  {
    name: "NCB Office",
    path: "NCB-Office/style.css",
    designer: "Nicholas Burns",
    portfolio: "#fixme",
  },
  {
    name: "Plant",
    path: "EH-plant/style.css",
    designer: "Emily Hanlon",
    portfolio: "#fixme",
  },
  {
    name: "Halloween",
    path: "GR-Halloween/style.css",
    designer: "Grayson Reska",
    portfolio: "https://grayson-reska-portfolio.netlify.app/",
  },
  {
    name: "Retro",
    path: "GR-Retro/style.css",
    designer: "Grayson Reska",
    portfolio: "https://grayson-reska-portfolio.netlify.app/",
  },
  {
    name: "Fall",
    path: "GR-Fall/style.css",
    designer: "Grayson Reska",
    highlight: true,
    portfolio: "https://grayson-reska-portfolio.netlify.app/",
  },
  {
    name: "Sandy",
    path: "KB-Sand/style.css",
    designer: "Khang B",
    portfolio: "#fixme",
  },
  {
    name: "Nature",
    path: "KB-Nature/style.css",
    designer: "Khang B",
    portfolio: "#fixme",
  },
  {
    name: "Door",
    path: "KB-Door/style.css",
    designer: "Khang B",
    portfolio: "#fixme",
  },
  {
    name: "The nightmare before christmas",
    path: "AK-halloween/style.css",
    designer: "Addison K.",
    portfolio: "#fixme",
  },
  {
    name: "Cotton-Candy",
    path: "Sams-Cotton-candy/style.css",
    designer: "Sam",
    portfolio: "#fixme",
  },
  {
    name: "Wall",
    path: "Joshua-Lopes-Wall/style.css",
    designer: "Joshua Lopes",
    portfolio: "#fixme",
  },
  {
    name: "Minecraft Pastel",
    path: "SB-Minecraft-Pastel/style.css",
    designer: "Sadie Bush",
    portfolio: "#fixme",
  },
  {
    name: "Spooky Month",
    path: "SB-Spooky-Month/style.css",
    designer: "Sadie Bush",
    portfolio: "#fixme",
  },
  {
    name: "Fish Tank",
    path: "SB-Fish-Tank/style.css",
    designer: "Sadie Bush",
    portfolio: "#fixme",
  },
  {
    name: "CyberShock-Miguel",
    path: "MO-CyberShock-Miguel/style.css",
    designer: "Miguel Osorio",
    portfolio: "#fixme",
  },
  {
    name: "city-Billy",
    path: "BL-city/style.css",
    designer: "Billy Lannan",
    portfolio: "https://BL-IACS-Portolio.netlify.app/",
  },
  {
    name: "80s",
    path: "RH-80s/style.css",
    designer: "Rylie Hegarty",
    portfolio: "https://rhwebdesignportfolio.netlify.app/ ",
    highlight: true,
  },
];
exports.styles = styles;
